/*
 * This file is generated by jOOQ.
 */
package io.roach.data.jooq;


import io.roach.data.jooq.tables.Account;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
