#############################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#############################
spring:
  profiles:
    active:
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: true
    connect-retries: 15
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: true
        connection:
          provider_disables_autocommit: false
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 128
          fetch_size: 128
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.CteValuesListBulkIdStrategy
        cache:
          use_minimal_puts: true
          use_second_level_cache: false
        session_factory:
          statement_inspector: io.roach.data.jpa.experimental.QueryInterceptor
  datasource:
    url: jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 0
      auto-commit: true
      transaction-isolation: TRANSACTION_SERIALIZABLE
      initialization-fail-timeout: -1
#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
