########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  output:
    ansi:
      enabled: ALWAYS
  r2dbc:
    url: r2dbc:postgresql://localhost:26257/roach_data?sslmode=disable
    username: root
    password:
server:
  port: 9090