########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  output:
    ansi:
      enabled: ALWAYS
  r2dbc:
    url: r2dbc:postgresql://kai-odin-11257.8nj.cockroachlabs.cloud:26257/kai-odin-11257.defaultdb?sslmode=verify-full
    username: guest
    password:
    pool:
      initial-size: 1
      max-size: 10
      max-idle-time: 30m
server:
  port: 9090